server:
  port: 9191

spring:
  application:
    name: dataloom-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 3
      logic-not-delete-value: 1

excel:
  upload:
    path: ./upload

logging:
  level:
    root: INFO
    com.demo.excel: DEBUG
